name: flutter_base_architecture
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^13.2.1
  talker_flutter: ^4.1.0

  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1

  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  gap: ^3.0.1

  sqlite3: ^2.4.0
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0

  drift_dev: ^2.16.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
